#
# https://github.com/P3TERX/IBM-CF-V2
#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: IBM Cloud Foundry - XRay

env:
  IBM_CF_API: https://api.us-south.cf.cloud.ibm.com
  IBM_CF_APP_MEM: 128M

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      IBM_CF_USERNAME: ${{ secrets.IBM_CF_USERNAME }}
      IBM_CF_PASSWORD: ${{ secrets.IBM_CF_PASSWORD }}
      IBM_CF_ORG_NAME: ${{ secrets.IBM_CF_ORG_NAME }}
      IBM_CF_SPACE_NAME: ${{ secrets.IBM_CF_SPACE_NAME }}
      IBM_CF_APP_NAME: ${{ secrets.IBM_CF_APP_NAME }}
      XR_VM_UUID: ${{ secrets.XR_VM_UUID }}
      XR_VL_UUID: ${{ secrets.XR_VL_UUID }}

    steps:

    - name: IBM-CF-XR Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Base package
      run: sudo apt install curl gnupg2 ca-certificates lsb-release libnss3-tools

    - name: Install Cloud Foundry CLI
      run: |
        curl -fsSL "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v7&source=github" | tar -zx
        sudo install -m 755 cf /usr/local/bin/cf
        cf version

    - name: Login to IBM Cloud Foundry
      run: |
        cf login \
              -a "${IBM_CF_API}" \
              -u "${IBM_CF_USERNAME}" \
              -p "${IBM_CF_PASSWORD}" \
              -o "${IBM_CF_ORG_NAME:-$IBM_CF_USERNAME}" \
              -s "${IBM_CF_SPACE_NAME:-dev}"

    - name: Download Cert
      run: |
        curl -fsSL "https://github.com/Dimitri2020007/IBM-CF-XR/raw/main/cert.zip"
        unzip cert.zip cert.crt cert.key
        sudo mv ./cert.crt /usr/local/bin/cert.crt
        sudo mv ./cert.key /usr/local/bin/cert.key
        rm cert.zip

    - name: Download Caddy Config
      run: |
        curl -fssL "https://raw.githubusercontent.com/Dimitri2020007/IBM-CF-XR/main/Caddyfile"
        sudo mv ./Caddyfile /usr/local/bin/Caddyfile

    - name: Download Caddy
      run: |
        curl -fssL "https://github.com/caddyserver/caddy/releases/download/v2.3.0/caddy_2.3.0_linux_amd64.tar.gz" | tar -zx
        sudo mv ./caddy /usr/local/bin/caddy
        caddy start --config /usr/local/bin/Caddyfile

    - name: Download Latest XRay
      run: |
        curl -fsSL "https://github.com/p4gefau1t/trojan-go/releases/download/v0.8.2/trojan-go-linux-amd64.zip" -o "trojan-go.zip"
        unzip trojan-go.zip trojan-go geosite.dat geoip.dat
        sudo mv ./geosite.dat /usr/local/bin/geosite.dat
        sudo mv ./geoip.dat /usr/local/bin/geoip.dat
        rm trojan-go.zip
        chmod -v 755 t*
        ./trojan-go -version
        mv trojan-go ${IBM_CF_APP_NAME}

    - name: Generate XRay Config File (VMess)
      if: ${{ env.XR_VM_UUID }}
      run: |
        base64 << P3TERX > config
        {
          "log": {
            "access": "none",
            "loglevel": "error"
          },
          "inbounds": [
            {
              "listen": "0.0.0.0",
              "port": 8079,
              "protocol": "vmess",
              "settings": {
                "clients": [
                  {
                    "id": "${XR_VM_UUID}",
                    "alterId": 64
                  }
                ]
              },
              "streamSettings": {
                "network":"ws",
                "wsSettings": {
                  "path": "/${XR_VM_UUID}-vmess"
                }
              }
            }
          ],
          "outbounds": [
            {
              "protocol": "freedom"
            }
          ]
        }
        P3TERX

    - name: Generate XRay Config File (TR-VLESS)
      if: ${{ env.XR_VL_UUID }}
      run: |
        base64 << P3TERX > config
        {
           "run_type": "server",
           "local_addr": "0.0.0.0",
           "local_port": 8080,
           "remote_addr": "127.0.0.1",
           "remote_port": 443,
           "password": [
              "${XR_VL_UUID}"
           ],
           "ssl": {
               "cert": "/usr/local/bin/cert.crt"
               "key": "/usr/local/bin/cert.key"
           },
           "router": {
               "enabled": true,
               "block": [
                   "geoip:private"
               ],
               "geoip": /usr/local/bin/geoip.dat
               "geosite": /usr/local/bin/geosite.dat
           },
           "websocket": {
             "enabled": true,
             "path": "/${XR_VL_UUID}-trojan"
           }
        }
        P3TERX

    - name: Generate Manifest File
      run: |
        cat << P3TERX > manifest.yml
        applications:
        - name: ${IBM_CF_APP_NAME}
          memory: ${IBM_CF_APP_MEM}
          random-route: true
          command: base64 -d config >  config.json; ./${IBM_CF_APP_NAME} ./trojan-go -config config.json
          buildpacks:
          - binary_buildpack
        P3TERX

    - name: Deploy Cloud Foundry App
      run: cf push
